on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '[0-9]+.[0-9]+.[0-9]*' # Push events to matching *, i.e. 1.0.0, 2.5.3

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'megane-auto-update.zip'