on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '[0-9]+.[0-9]+.[0-9]*' # Push events to matching *, i.e. 1.0.0, 2.5.3

name: Upload Release Asset

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        name: Easy Zip Files
        with:
          files: /
          dest: megane-auto-update.zip