on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '[0-9]+.[0-9]+.[0-9]*' # Push events to matching *, i.e. 1.0.0, 2.5.3

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'megane-auto-update.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'